const data = {
    products: [
      {
        name: 'Free Shirt',
        slug: 'free-shirt',
        category: 'Shirts',
        image: 'https://res.cloudinary.com/sentech/image/upload/v1656436278/ikiguy_media/ihcvvrsdagudqlmahkph.jpg',
        price: 70,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        name: 'Fit Shirt',
        category: 'Shirts',
        slug: 'free-polo',
        image: 'https://res.cloudinary.com/sentech/image/upload/v1656436107/ikiguy_media/pwdfkxml4p93v9rgcl95.jpg',
        price: 80,
        brand: 'Adidas',
        rating: 4.2,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        name: 'Slim Shirt',
        slug: 'shirt',
        category: 'Shirts',
        image: 'https://res.cloudinary.com/sentech/image/upload/v1656436090/ikiguy_media/sdcvr0abhvzl5ky0c5ue.jpg',
        price: 90,
        brand: 'Raymond',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        name: 'Golf Pants',
        category: 'Pants',
        slug: 'free-pants',
        image: 'https://res.cloudinary.com/sentech/image/upload/v1656609525/ikiguy_media/hyhlspgje5mul6zmeg3o.jpg',
        price: 90,
        brand: 'Oliver',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Smart looking pants',
      },
      {
        name: 'Fit Pants',
        category: 'Pants',
        slug: 'cargo-pants',
        image: '/images/pants2.jpg',
        price: 95,
        brand: 'Zara',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular pants',
      },
      {
        name: 'Classic Pants',
        slug: 'lv-pants',
        category: 'Pants',
        image: 'https://res.cloudinary.com/sentech/image/upload/v1656609525/ikiguy_media/hyhlspgje5mul6zmeg3o.jpg',
        price: 75,
        brand: 'Casely',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular pants',
      },
    ],
  };
  export default data;